### ISSUE TITLE
NC_017644.1 - Escherichia coli

### ISSUE THREAD

**Issue by kwongj** [refweak/refweak#3]
The paper: https://www.ncbi.nlm.nih.gov/pubmed/21685291
The criticism: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0104400

The ST131 E. coli genome NA114 appears to be misassembled:
* in their paper, the authors describe methods including sequencing with GA IIx, assembly with Velvet, with contigs ordered against another reference genome in Mauve; no assembly checking e.g. optical mapping was performed - it would be unusual to close a 5.1 Mbp genome without long read sequencing or wet lab gap closure
* the authors appear to have simply joined their contigs to form a single contig
* the chromosome is almost 200kb smaller than other closely related chromosomes
* there are several gaps in the chromosome compared to closely related genomes, including three large genomic islands (see PLoS One paper)

Torst and I contacted the authors for an explanation a few years ago, and their response was "get rid of him"!

![image](https://cloud.githubusercontent.com/assets/7855976/19995731/241e67f4-a2ae-11e6-99bf-4a7bf0544f5d.png)

**Comment by andrewjpage** [comment]
Yep thats there already. @tseemann filled me in.

**Comment by andrewjpage** [comment]
Yep thats there already. @tseemann filled me in.

**Comment by andrewjpage** [comment]
Yep thats there already. @tseemann filled me in.
