### ISSUE TITLE
please add JSVT00000000.1

### ISSUE THREAD

**Issue by kwongj** [refweak/refweak#4]
**Genome accession:**
JSVT00000000.1

**Genome announcement paper:**
https://www.ncbi.nlm.nih.gov/pubmed/26358609

**Reason for inclusion:**
Supposed to be a "Draft Genome Sequence of a vanA-Type Vancomycin-Resistant Reference Strain, Enterococcus faecium ATCC 51559". This strain is commonly used in laboratories as a vanA VRE reference strain. Unfortunately, the uploaded genome does not contain the vanA operon and thus is not vanA VRE. It is possible the plasmid was lost prior to sequencing, but this strain should be resequenced and resubmitted.

**Comment by andrewjpage** [comment]
Thanks, added
